package com.sondeosglobal.simpleserver.handlers;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.io.OutputStreamWriter;
import java.util.Random;
import java.util.Vector;

import org.apache.log4j.Logger;

import com.sun.net.httpserver.HttpExchange;
import com.sun.net.httpserver.HttpHandler;

@SuppressWarnings("restriction")
public class OoredooSolicitarBillingHandler implements HttpHandler {
	Logger	log = Logger.getRootLogger();
	
	private static String CODIGO_0		    = "<?xml version=\"1.0\" encoding=\"UTF-8\"?><ocsResponse><sequenceNo>12345</sequenceNo><scpTransactionId>h8d87h213873</scpTransactionId><callingParty>9810599383</callingParty><serviceType> CRBT</serviceType><serviceId>CRBT</serviceId><subsType>1</subsType><chargeAmount>30</chargeAmount><result>OK</result><errorCode>0</errorCode><serviceUsage></serviceUsage><accountBalance>100.00</accountBalance><requestedPlan>-1</requestedPlan><appliedPlan>-1</appliedPlan><discountPlan>-1</discountPlan><optionalParameter1>-1</optionalParameter1><optionalParameter2>-1</optionalParameter2><optionalParameter3>-1</optionalParameter3><optionalParameter4>-1</optionalParameter4><optionalParameter5>-1</optionalParameter5><optionalParameter6>-1</optionalParameter6><optionalParameter7>-1</optionalParameter7><optionalParameter8>-1</optionalParameter8><optionalParameter9>-1</optionalParameter9><optionalParameter10>-1</optionalParameter10><optionalParameter11>-1</optionalParameter11></ocsResponse>";
	private static String CODIGO_R9001		= "<?xml version=\"1.0\" encoding=\"UTF-8\"?><ocsResponse><sequenceNo>12345</sequenceNo><scpTransactionId>h8d87h213873</scpTransactionId><callingParty>9810599383</callingParty><serviceType> CRBT</serviceType><serviceId>CRBT</serviceId><subsType>1</subsType><chargeAmount>30</chargeAmount><result>OK</result><errorCode>R9001</errorCode><serviceUsage></serviceUsage><accountBalance>100.00</accountBalance><requestedPlan>-1</requestedPlan><appliedPlan>-1</appliedPlan><discountPlan>-1</discountPlan><optionalParameter1>-1</optionalParameter1><optionalParameter2>-1</optionalParameter2><optionalParameter3>-1</optionalParameter3><optionalParameter4>-1</optionalParameter4><optionalParameter5>-1</optionalParameter5><optionalParameter6>-1</optionalParameter6><optionalParameter7>-1</optionalParameter7><optionalParameter8>-1</optionalParameter8><optionalParameter9>-1</optionalParameter9><optionalParameter10>-1</optionalParameter10><optionalParameter11>-1</optionalParameter11></ocsResponse>";
	private static String CODIGO_R9002		= "<?xml version=\"1.0\" encoding=\"UTF-8\"?><ocsResponse><sequenceNo>12345</sequenceNo><scpTransactionId>h8d87h213873</scpTransactionId><callingParty>9810599383</callingParty><serviceType> CRBT</serviceType><serviceId>CRBT</serviceId><subsType>1</subsType><chargeAmount>30</chargeAmount><result>OK</result><errorCode>R9002</errorCode><serviceUsage></serviceUsage><accountBalance>100.00</accountBalance><requestedPlan>-1</requestedPlan><appliedPlan>-1</appliedPlan><discountPlan>-1</discountPlan><optionalParameter1>-1</optionalParameter1><optionalParameter2>-1</optionalParameter2><optionalParameter3>-1</optionalParameter3><optionalParameter4>-1</optionalParameter4><optionalParameter5>-1</optionalParameter5><optionalParameter6>-1</optionalParameter6><optionalParameter7>-1</optionalParameter7><optionalParameter8>-1</optionalParameter8><optionalParameter9>-1</optionalParameter9><optionalParameter10>-1</optionalParameter10><optionalParameter11>-1</optionalParameter11></ocsResponse>";
	private static String CODIGO_R9003		= "<?xml version=\"1.0\" encoding=\"UTF-8\"?><ocsResponse><sequenceNo>12345</sequenceNo><scpTransactionId>h8d87h213873</scpTransactionId><callingParty>9810599383</callingParty><serviceType> CRBT</serviceType><serviceId>CRBT</serviceId><subsType>1</subsType><chargeAmount>30</chargeAmount><result>OK</result><errorCode>R9003</errorCode><serviceUsage></serviceUsage><accountBalance>100.00</accountBalance><requestedPlan>-1</requestedPlan><appliedPlan>-1</appliedPlan><discountPlan>-1</discountPlan><optionalParameter1>-1</optionalParameter1><optionalParameter2>-1</optionalParameter2><optionalParameter3>-1</optionalParameter3><optionalParameter4>-1</optionalParameter4><optionalParameter5>-1</optionalParameter5><optionalParameter6>-1</optionalParameter6><optionalParameter7>-1</optionalParameter7><optionalParameter8>-1</optionalParameter8><optionalParameter9>-1</optionalParameter9><optionalParameter10>-1</optionalParameter10><optionalParameter11>-1</optionalParameter11></ocsResponse>";
	private static String CODIGO_R9004		= "<?xml version=\"1.0\" encoding=\"UTF-8\"?><ocsResponse><sequenceNo>12345</sequenceNo><scpTransactionId>h8d87h213873</scpTransactionId><callingParty>9810599383</callingParty><serviceType> CRBT</serviceType><serviceId>CRBT</serviceId><subsType>1</subsType><chargeAmount>30</chargeAmount><result>OK</result><errorCode>R9004</errorCode><serviceUsage></serviceUsage><accountBalance>100.00</accountBalance><requestedPlan>-1</requestedPlan><appliedPlan>-1</appliedPlan><discountPlan>-1</discountPlan><optionalParameter1>-1</optionalParameter1><optionalParameter2>-1</optionalParameter2><optionalParameter3>-1</optionalParameter3><optionalParameter4>-1</optionalParameter4><optionalParameter5>-1</optionalParameter5><optionalParameter6>-1</optionalParameter6><optionalParameter7>-1</optionalParameter7><optionalParameter8>-1</optionalParameter8><optionalParameter9>-1</optionalParameter9><optionalParameter10>-1</optionalParameter10><optionalParameter11>-1</optionalParameter11></ocsResponse>";
	private static String CODIGO_R9005		= "<?xml version=\"1.0\" encoding=\"UTF-8\"?><ocsResponse><sequenceNo>12345</sequenceNo><scpTransactionId>h8d87h213873</scpTransactionId><callingParty>9810599383</callingParty><serviceType> CRBT</serviceType><serviceId>CRBT</serviceId><subsType>1</subsType><chargeAmount>30</chargeAmount><result>OK</result><errorCode>R9005</errorCode><serviceUsage></serviceUsage><accountBalance>100.00</accountBalance><requestedPlan>-1</requestedPlan><appliedPlan>-1</appliedPlan><discountPlan>-1</discountPlan><optionalParameter1>-1</optionalParameter1><optionalParameter2>-1</optionalParameter2><optionalParameter3>-1</optionalParameter3><optionalParameter4>-1</optionalParameter4><optionalParameter5>-1</optionalParameter5><optionalParameter6>-1</optionalParameter6><optionalParameter7>-1</optionalParameter7><optionalParameter8>-1</optionalParameter8><optionalParameter9>-1</optionalParameter9><optionalParameter10>-1</optionalParameter10><optionalParameter11>-1</optionalParameter11></ocsResponse>";
	private static String CODIGO_R9006		= "<?xml version=\"1.0\" encoding=\"UTF-8\"?><ocsResponse><sequenceNo>12345</sequenceNo><scpTransactionId>h8d87h213873</scpTransactionId><callingParty>9810599383</callingParty><serviceType> CRBT</serviceType><serviceId>CRBT</serviceId><subsType>1</subsType><chargeAmount>30</chargeAmount><result>OK</result><errorCode>R9006</errorCode><serviceUsage></serviceUsage><accountBalance>100.00</accountBalance><requestedPlan>-1</requestedPlan><appliedPlan>-1</appliedPlan><discountPlan>-1</discountPlan><optionalParameter1>-1</optionalParameter1><optionalParameter2>-1</optionalParameter2><optionalParameter3>-1</optionalParameter3><optionalParameter4>-1</optionalParameter4><optionalParameter5>-1</optionalParameter5><optionalParameter6>-1</optionalParameter6><optionalParameter7>-1</optionalParameter7><optionalParameter8>-1</optionalParameter8><optionalParameter9>-1</optionalParameter9><optionalParameter10>-1</optionalParameter10><optionalParameter11>-1</optionalParameter11></ocsResponse>";
	private static String CODIGO_R9007		= "<?xml version=\"1.0\" encoding=\"UTF-8\"?><ocsResponse><sequenceNo>12345</sequenceNo><scpTransactionId>h8d87h213873</scpTransactionId><callingParty>9810599383</callingParty><serviceType> CRBT</serviceType><serviceId>CRBT</serviceId><subsType>1</subsType><chargeAmount>30</chargeAmount><result>OK</result><errorCode>R9007</errorCode><serviceUsage></serviceUsage><accountBalance>100.00</accountBalance><requestedPlan>-1</requestedPlan><appliedPlan>-1</appliedPlan><discountPlan>-1</discountPlan><optionalParameter1>-1</optionalParameter1><optionalParameter2>-1</optionalParameter2><optionalParameter3>-1</optionalParameter3><optionalParameter4>-1</optionalParameter4><optionalParameter5>-1</optionalParameter5><optionalParameter6>-1</optionalParameter6><optionalParameter7>-1</optionalParameter7><optionalParameter8>-1</optionalParameter8><optionalParameter9>-1</optionalParameter9><optionalParameter10>-1</optionalParameter10><optionalParameter11>-1</optionalParameter11></ocsResponse>";
	private static String CODIGO_R9008		= "<?xml version=\"1.0\" encoding=\"UTF-8\"?><ocsResponse><sequenceNo>12345</sequenceNo><scpTransactionId>h8d87h213873</scpTransactionId><callingParty>9810599383</callingParty><serviceType> CRBT</serviceType><serviceId>CRBT</serviceId><subsType>1</subsType><chargeAmount>30</chargeAmount><result>OK</result><errorCode>R9008</errorCode><serviceUsage></serviceUsage><accountBalance>100.00</accountBalance><requestedPlan>-1</requestedPlan><appliedPlan>-1</appliedPlan><discountPlan>-1</discountPlan><optionalParameter1>-1</optionalParameter1><optionalParameter2>-1</optionalParameter2><optionalParameter3>-1</optionalParameter3><optionalParameter4>-1</optionalParameter4><optionalParameter5>-1</optionalParameter5><optionalParameter6>-1</optionalParameter6><optionalParameter7>-1</optionalParameter7><optionalParameter8>-1</optionalParameter8><optionalParameter9>-1</optionalParameter9><optionalParameter10>-1</optionalParameter10><optionalParameter11>-1</optionalParameter11></ocsResponse>";
	private static String CODIGO_R9009		= "<?xml version=\"1.0\" encoding=\"UTF-8\"?><ocsResponse><sequenceNo>12345</sequenceNo><scpTransactionId>h8d87h213873</scpTransactionId><callingParty>9810599383</callingParty><serviceType> CRBT</serviceType><serviceId>CRBT</serviceId><subsType>1</subsType><chargeAmount>30</chargeAmount><result>OK</result><errorCode>R9009</errorCode><serviceUsage></serviceUsage><accountBalance>100.00</accountBalance><requestedPlan>-1</requestedPlan><appliedPlan>-1</appliedPlan><discountPlan>-1</discountPlan><optionalParameter1>-1</optionalParameter1><optionalParameter2>-1</optionalParameter2><optionalParameter3>-1</optionalParameter3><optionalParameter4>-1</optionalParameter4><optionalParameter5>-1</optionalParameter5><optionalParameter6>-1</optionalParameter6><optionalParameter7>-1</optionalParameter7><optionalParameter8>-1</optionalParameter8><optionalParameter9>-1</optionalParameter9><optionalParameter10>-1</optionalParameter10><optionalParameter11>-1</optionalParameter11></ocsResponse>";
	private static String CODIGO_R9010		= "<?xml version=\"1.0\" encoding=\"UTF-8\"?><ocsResponse><sequenceNo>12345</sequenceNo><scpTransactionId>h8d87h213873</scpTransactionId><callingParty>9810599383</callingParty><serviceType> CRBT</serviceType><serviceId>CRBT</serviceId><subsType>1</subsType><chargeAmount>30</chargeAmount><result>OK</result><errorCode>R9010</errorCode><serviceUsage></serviceUsage><accountBalance>100.00</accountBalance><requestedPlan>-1</requestedPlan><appliedPlan>-1</appliedPlan><discountPlan>-1</discountPlan><optionalParameter1>-1</optionalParameter1><optionalParameter2>-1</optionalParameter2><optionalParameter3>-1</optionalParameter3><optionalParameter4>-1</optionalParameter4><optionalParameter5>-1</optionalParameter5><optionalParameter6>-1</optionalParameter6><optionalParameter7>-1</optionalParameter7><optionalParameter8>-1</optionalParameter8><optionalParameter9>-1</optionalParameter9><optionalParameter10>-1</optionalParameter10><optionalParameter11>-1</optionalParameter11></ocsResponse>";
	private static String CODIGO_R9011		= "<?xml version=\"1.0\" encoding=\"UTF-8\"?><ocsResponse><sequenceNo>12345</sequenceNo><scpTransactionId>h8d87h213873</scpTransactionId><callingParty>9810599383</callingParty><serviceType> CRBT</serviceType><serviceId>CRBT</serviceId><subsType>1</subsType><chargeAmount>30</chargeAmount><result>OK</result><errorCode>R9011</errorCode><serviceUsage></serviceUsage><accountBalance>100.00</accountBalance><requestedPlan>-1</requestedPlan><appliedPlan>-1</appliedPlan><discountPlan>-1</discountPlan><optionalParameter1>-1</optionalParameter1><optionalParameter2>-1</optionalParameter2><optionalParameter3>-1</optionalParameter3><optionalParameter4>-1</optionalParameter4><optionalParameter5>-1</optionalParameter5><optionalParameter6>-1</optionalParameter6><optionalParameter7>-1</optionalParameter7><optionalParameter8>-1</optionalParameter8><optionalParameter9>-1</optionalParameter9><optionalParameter10>-1</optionalParameter10><optionalParameter11>-1</optionalParameter11></ocsResponse>";
	private static String CODIGO_R9012		= "<?xml version=\"1.0\" encoding=\"UTF-8\"?><ocsResponse><sequenceNo>12345</sequenceNo><scpTransactionId>h8d87h213873</scpTransactionId><callingParty>9810599383</callingParty><serviceType> CRBT</serviceType><serviceId>CRBT</serviceId><subsType>1</subsType><chargeAmount>30</chargeAmount><result>OK</result><errorCode>R9012</errorCode><serviceUsage></serviceUsage><accountBalance>100.00</accountBalance><requestedPlan>-1</requestedPlan><appliedPlan>-1</appliedPlan><discountPlan>-1</discountPlan><optionalParameter1>-1</optionalParameter1><optionalParameter2>-1</optionalParameter2><optionalParameter3>-1</optionalParameter3><optionalParameter4>-1</optionalParameter4><optionalParameter5>-1</optionalParameter5><optionalParameter6>-1</optionalParameter6><optionalParameter7>-1</optionalParameter7><optionalParameter8>-1</optionalParameter8><optionalParameter9>-1</optionalParameter9><optionalParameter10>-1</optionalParameter10><optionalParameter11>-1</optionalParameter11></ocsResponse>";
	private static String CODIGO_R9013		= "<?xml version=\"1.0\" encoding=\"UTF-8\"?><ocsResponse><sequenceNo>12345</sequenceNo><scpTransactionId>h8d87h213873</scpTransactionId><callingParty>9810599383</callingParty><serviceType> CRBT</serviceType><serviceId>CRBT</serviceId><subsType>1</subsType><chargeAmount>30</chargeAmount><result>OK</result><errorCode>R9013</errorCode><serviceUsage></serviceUsage><accountBalance>100.00</accountBalance><requestedPlan>-1</requestedPlan><appliedPlan>-1</appliedPlan><discountPlan>-1</discountPlan><optionalParameter1>-1</optionalParameter1><optionalParameter2>-1</optionalParameter2><optionalParameter3>-1</optionalParameter3><optionalParameter4>-1</optionalParameter4><optionalParameter5>-1</optionalParameter5><optionalParameter6>-1</optionalParameter6><optionalParameter7>-1</optionalParameter7><optionalParameter8>-1</optionalParameter8><optionalParameter9>-1</optionalParameter9><optionalParameter10>-1</optionalParameter10><optionalParameter11>-1</optionalParameter11></ocsResponse>";
	private static String CODIGO_R9014		= "<?xml version=\"1.0\" encoding=\"UTF-8\"?><ocsResponse><sequenceNo>12345</sequenceNo><scpTransactionId>h8d87h213873</scpTransactionId><callingParty>9810599383</callingParty><serviceType> CRBT</serviceType><serviceId>CRBT</serviceId><subsType>1</subsType><chargeAmount>30</chargeAmount><result>OK</result><errorCode>R9014</errorCode><serviceUsage></serviceUsage><accountBalance>100.00</accountBalance><requestedPlan>-1</requestedPlan><appliedPlan>-1</appliedPlan><discountPlan>-1</discountPlan><optionalParameter1>-1</optionalParameter1><optionalParameter2>-1</optionalParameter2><optionalParameter3>-1</optionalParameter3><optionalParameter4>-1</optionalParameter4><optionalParameter5>-1</optionalParameter5><optionalParameter6>-1</optionalParameter6><optionalParameter7>-1</optionalParameter7><optionalParameter8>-1</optionalParameter8><optionalParameter9>-1</optionalParameter9><optionalParameter10>-1</optionalParameter10><optionalParameter11>-1</optionalParameter11></ocsResponse>";
	private static String CODIGO_R9015		= "<?xml version=\"1.0\" encoding=\"UTF-8\"?><ocsResponse><sequenceNo>12345</sequenceNo><scpTransactionId>h8d87h213873</scpTransactionId><callingParty>9810599383</callingParty><serviceType> CRBT</serviceType><serviceId>CRBT</serviceId><subsType>1</subsType><chargeAmount>30</chargeAmount><result>OK</result><errorCode>R9015</errorCode><serviceUsage></serviceUsage><accountBalance>100.00</accountBalance><requestedPlan>-1</requestedPlan><appliedPlan>-1</appliedPlan><discountPlan>-1</discountPlan><optionalParameter1>-1</optionalParameter1><optionalParameter2>-1</optionalParameter2><optionalParameter3>-1</optionalParameter3><optionalParameter4>-1</optionalParameter4><optionalParameter5>-1</optionalParameter5><optionalParameter6>-1</optionalParameter6><optionalParameter7>-1</optionalParameter7><optionalParameter8>-1</optionalParameter8><optionalParameter9>-1</optionalParameter9><optionalParameter10>-1</optionalParameter10><optionalParameter11>-1</optionalParameter11></ocsResponse>";
	private static String CODIGO_R9016		= "<?xml version=\"1.0\" encoding=\"UTF-8\"?><ocsResponse><sequenceNo>12345</sequenceNo><scpTransactionId>h8d87h213873</scpTransactionId><callingParty>9810599383</callingParty><serviceType> CRBT</serviceType><serviceId>CRBT</serviceId><subsType>1</subsType><chargeAmount>30</chargeAmount><result>OK</result><errorCode>R9016</errorCode><serviceUsage></serviceUsage><accountBalance>100.00</accountBalance><requestedPlan>-1</requestedPlan><appliedPlan>-1</appliedPlan><discountPlan>-1</discountPlan><optionalParameter1>-1</optionalParameter1><optionalParameter2>-1</optionalParameter2><optionalParameter3>-1</optionalParameter3><optionalParameter4>-1</optionalParameter4><optionalParameter5>-1</optionalParameter5><optionalParameter6>-1</optionalParameter6><optionalParameter7>-1</optionalParameter7><optionalParameter8>-1</optionalParameter8><optionalParameter9>-1</optionalParameter9><optionalParameter10>-1</optionalParameter10><optionalParameter11>-1</optionalParameter11></ocsResponse>";
	private static String CODIGO_R9017		= "<?xml version=\"1.0\" encoding=\"UTF-8\"?><ocsResponse><sequenceNo>12345</sequenceNo><scpTransactionId>h8d87h213873</scpTransactionId><callingParty>9810599383</callingParty><serviceType> CRBT</serviceType><serviceId>CRBT</serviceId><subsType>1</subsType><chargeAmount>30</chargeAmount><result>OK</result><errorCode>R9017</errorCode><serviceUsage></serviceUsage><accountBalance>100.00</accountBalance><requestedPlan>-1</requestedPlan><appliedPlan>-1</appliedPlan><discountPlan>-1</discountPlan><optionalParameter1>-1</optionalParameter1><optionalParameter2>-1</optionalParameter2><optionalParameter3>-1</optionalParameter3><optionalParameter4>-1</optionalParameter4><optionalParameter5>-1</optionalParameter5><optionalParameter6>-1</optionalParameter6><optionalParameter7>-1</optionalParameter7><optionalParameter8>-1</optionalParameter8><optionalParameter9>-1</optionalParameter9><optionalParameter10>-1</optionalParameter10><optionalParameter11>-1</optionalParameter11></ocsResponse>";

	
	private String[] respuestasPosibles = {CODIGO_0, CODIGO_R9001, CODIGO_R9002, CODIGO_R9003, CODIGO_R9004, CODIGO_R9005, CODIGO_R9006, CODIGO_R9007, CODIGO_R9008, CODIGO_R9009, CODIGO_R9010, CODIGO_R9011, CODIGO_R9012, CODIGO_R9013, CODIGO_R9014, CODIGO_R9015, CODIGO_R9016, CODIGO_R9017};

	protected Vector<IMesssageListener> listeners = new Vector<IMesssageListener>();
	
	public void handle(HttpExchange t) throws IOException {
		log.info("Nueva request");
		
		String response = getRandomResponse();
        BufferedReader br = new BufferedReader(new InputStreamReader(t.getRequestBody(), "UTF-8"));
        
        OutputStream os = t.getResponseBody();
        BufferedWriter bw = new BufferedWriter(new OutputStreamWriter(os));
        bw.write(response);
        
        
        t.sendResponseHeaders(200, response.length());
        bw.close();
        br.close();
        
        t.close();
		
	}
	
	private String getRandomResponse() {
		log.info("getRandomResponse");
		Random rand = new Random();
		String response;
		
		int techo = respuestasPosibles.length;
		int indiceRand = rand.nextInt(techo) + 1;
		
		response = respuestasPosibles[indiceRand - 1];
		
		log.info("Response: " + response);
		return response;
		
	}
	
}
